name: Documentation

on:
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Python 2.7 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install and Build 🔧
        run: |
          sudo apt install doxygen graphviz && pip install doxypypy && which doxypypy
          doxygen

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: docs/html
          single-commit: true
