name: Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Python 2.7 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip && pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install modules to test 🔧
        run: |
          pip install -e path_planner/src/
          pip install -e controller/src/

      - name: Test with pytest 🚀
        run: |
          pytest -v
